### PR TITLE
Fix typos (fixes #855)

### LINKED ISSUE #855: typo: `varibles` → `variables`
https://github.com/syncthing/syncthing/blob/e74674a019fd6289c312dc9b94bd547eb180aeac/man/syncthing-config.5#L89

### PR DESCRIPTION
**Pull request by deining**
This PR fixes a few typos and grammar errors I spotted.
This PR also closes #855.

### CODE REVIEW

**Review by bentolor — APPROVED** [review]
LGTM

File: _script/histver/synver.go [hunk 1]
```diff
@@ -37,7 +37,7 @@ func main() {
 	var table []*tableRow
 	fd, err := os.Open(*versionsFile)
 	if os.IsNotExist(err) {
-		// File doesn't exist yet. That's allright.
+		// File doesn't exist yet. That's all right.
```
Comment (imsodin) [inline _script/histver/synver.go:40]:
```suggestion
		// File doesn't exist yet. That's alright.
```

Comment (deining) [reply _script/histver/synver.go]: Changed as requested.

**Review by acolomb — APPROVED** [review]
